### ISSUE TITLE
Question: Is this project still maintained?

### ISSUE THREAD

**Issue by NachoVazquez** [sor4chi/hono-do#34]
Hi @sor4chi! Thanks for creating this package. It is exciting.

I notice that it hasn't been maintained in some time. Are you still planning on keeping it?

I intend to help you maintain it; I guess my question is if you are interested in active work on it or if I should focus on my fork.

Best regard!

**Comment by sor4chi** [comment]
Hi, @NachoVazquez !
Thanks for the very nice issue.

I am not sure if I want to maintain it. I think it's technically interesting, but it doesn't seem to be used much.
If I had feedback I could proceed with development...

By the way, did you know that Cloudflare Workers RPC is out?
The purpose of Hono DO was to make it easier to handle the difficult syntax unique to Durable Objects using Hono, but now that RPC is available and DO methods can be invoked type-safe, I think the benefits of using Hono DO are disappearing.

**Comment by NachoVazquez** [comment]
I just read about Cloudflare Workers RPC after you mentioned it. It's fascinating indeed; however, my primary use case is Websockets with Hibernation, for which RPC is not a big help unless I'm ignoring something.

I tried your project for that purpose, and it works great. I worry you are using some old versions of Hono and Wrangler, so if that's an easy update from your side, I will be grateful; if you cannot, I will try to do it myself. 

I will also offer you a symbolic sponsor if you decide to continue maintaining the project, at least keeping its dependencies current.

**Comment by NachoVazquez** [comment]
I was able to use parts of your examples to make DO with Hibernation Websocket work without `hono-do` so that was already a big help from your side!

**Comment by sor4chi** [comment]
Thank you very much.
I just set up a Dependsbot to follow Hono's release.
I am planning to update dependencies on a weekly basis for now.

For now, I have raised the Hono dependency to 4.2.7 (latest) on a trial basis.

This is a sudden version update, so please give us time to verify it before releasing it.

But I have released it with `next` tag, so you can use it if you like.
[hono-do@0.0.0-next-20240424181558](https://www.npmjs.com/package/hono-do/v/0.0.0-next-20240424181558)

**Comment by NachoVazquez** [comment]
Wonderful! I appreciate you! Thanks!

**Comment by sor4chi** [comment]
You're welcome.
Thank you for sponsoring me!

**Comment by sor4chi** [comment]
Hi @NachoVazquez!
I've released [hono-do@2.0.0](https://github.com/sor4chi/hono-do/releases/tag/hono-do%402.0.0)!
Please check it out!

**Comment by NachoVazquez** [comment]
Amazing! Thanks @sor4chi . I'll check it out in the morning
